language: r
sudo: false
warnings_are_errors: false

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

r_github_packages:
  - hadley/testthat
  - hadley/devtools
  - jerome/jsonlite
  - hadley/httr
  - hadley/dplyr
  - klutometis/roxygen
  - jimhester/covr
  - rstudio/rmarkdown
  - yihui/knitr

notifications:
  email:
    on_success: never
    on_failure: always
    
after_success:
  - Rscript -e 'library(covr);coveralls()'
