language: r
sudo: false
warnings_are_errors: false
cache: packages
r:
  - release
  - devel
  - oldrel
  
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

r_github_packages:
  - r-lib/covr

notifications:
  email:
    on_success: never
    on_failure: always
    
after_success:
  - Rscript -e 'library(covr);covr::coveralls()'
