language: r
sudo: false
warnings_are_errors: false
cache: packages
r:
  - release
  - devel

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

r_packages:
  - covr

r_github_packages:
  - jimhester/lintr

after_script:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
  
after_success:
  - Rscript -e 'library(covr);covr::codecov(token = "99e5807c-72f3-445e-830c-79c132f1b5e7")'
  - Rscript -e 'library(covr);covr::coveralls(repo_token = "OSlPWUZnMzfy0kf5hMV12uBYI8nPaL3Cd")'
  
notifications:
  email:
    on_success: never
    on_failure: always
